### ISSUE TITLE
IS this still supported in Plex. Getting an internal error check logs.

### ISSUE THREAD

**Issue by duncanjc** [srazer/FindMissing.bundle#8]
Can't get this plug into work, I either get this channel is not available or Internal Error check logs.

Can't find any logs in %localappdata%Plex Media Server plugins or logs.

**Comment by ukdtom** [comment]
Haven't seen @srazer around for a long time sadly...

When said, I strongly suspect, that you might have installed the plug-in below the Resource dir?

And when said, the functionality of this plugin is also to be found in WebTools FindMedia

**Comment by duncanjc** [comment]
Hi,

Thanks for the feedback. I found another way round my issue. I used export tool with the levels set to 666, this gave the file location. So if the file location was missing I could see the missing data.
Duncan

**Comment by ukdtom** [comment]
Still would have been a lot more easy to use WebTools for this....

A lot faster, and would detect both missing from the file system, as well as missing from the database, but present in the file system.

About 100% faster than ExportTools, and I should know, since I wrote both
